### ISSUE TITLE
There's an error occurred with 502 when trying to GET with activityId

### ISSUE THREAD

**Issue by mmmmmob** [JSD6G8/backend#5]
**Where does it occur:**
On the frontend in an edit activity page which parse activityId to params value, 

**Steps used to verify the problem**
console.log at frontend got the correct activityId (also on url) but the axios.get which take params value from url as endpoint variable to the api output an error with 502 Bad Gateway on Render

**Suggestions**
Not sure if it caused by [CORS](https://medium.com/neverrest/cors-%E0%B8%A3%E0%B8%A7%E0%B8%A1%E0%B8%A7%E0%B8%B4%E0%B8%98%E0%B8%B5%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%81%E0%B8%81%E0%B9%89%E0%B9%84%E0%B8%82%E0%B8%9B%E0%B8%B1%E0%B8%8D%E0%B8%AB%E0%B8%B2-cors-%E0%B8%97%E0%B8%B5%E0%B9%88-web-developer-%E0%B8%95%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B9%80%E0%B8%88%E0%B8%AD-5afb6a9e742f) bc when using localhost environment to connect it output this error:

```
edit:1 Access to XMLHttpRequest at 'https://jsd6-loglife-backend.onrender.com/activities/65bc60849f6f0af313259a9b' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

```

**Comment by prutmongkol** [comment]
A bug was found in getActivity(). activityId was called before declaration.

It should work now.

See below for more details:
https://github.com/JSD6G8/backend/commit/30cfccc17dcab40b301efcaf8e78ec880d915150

**Comment by mmmmmob** [comment]
Works fine now! Thanks krubb

![image](https://github.com/JSD6G8/backend/assets/141404845/a9843c34-a6f4-4e7a-87b3-0b8b5afcd011)
